# Generated by Django 6.0.1 on 2026-08-16 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, choices=[('kerry', 'Kerry Express'), ('flash', 'Flash Express'), ('jnt', 'J&T Express'), ('thailand_post', 'ไปรษณีย์ไทย'), ('other', 'อื่นๆ')], max_length=20, verbose_name='ขนส่ง'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='เลขพัสดุ'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'ชำระแล้ว กำลังเตรียมสินค้า'), ('shipped', 'จัดส่งแล้ว'), ('in_transit', 'กำลังนำส่ง'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิก'), ('failed', 'ล้มเหลว'), ('expired', 'หมดอายุ')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'ชำระแล้ว กำลังเตรียมสินค้า'), ('shipped', 'จัดส่งแล้ว'), ('in_transit', 'กำลังนำส่ง'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิก'), ('failed', 'ล้มเหลว'), ('expired', 'หมดอายุ')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='store.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
