# Generated by Django 6.0.1 on 2026-08-24 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_options_order_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อพืช')),
                ('grow_days', models.PositiveIntegerField(verbose_name='จำนวนวันจนเก็บเกี่ยว')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='รูปภาพ')),
            ],
            options={
                'verbose_name': 'พืช',
                'verbose_name_plural': 'รายการพืช',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='รหัสแปลง')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อแปลง')),
                ('size', models.CharField(max_length=50, verbose_name='ขนาด')),
                ('sun_type', models.CharField(max_length=100, verbose_name='แสงแดด')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ราคา (฿/วัน)')),
                ('image', models.CharField(max_length=200, verbose_name='รูปภาพ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'แปลง',
                'verbose_name_plural': 'แปลงผัก',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ชื่อลูกค้า')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทร')),
                ('start_date', models.DateField(verbose_name='วันเริ่มปลูก')),
                ('harvest_date', models.DateField(verbose_name='วันคาดว่าเก็บเกี่ยว')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'ยืนยันการจองแล้ว'), ('growing', 'กำลังปลูก'), ('ready_to_harvest', 'พร้อมเก็บเกี่ยว'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('expired', 'หมดอายุ')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('charge_id', models.CharField(blank=True, max_length=100, verbose_name='Charge ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='store.plant', verbose_name='พืช')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='store.plot', verbose_name='แปลง')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plot_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การจองแปลง',
                'verbose_name_plural': 'การจองแปลง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlotBookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'ยืนยันการจองแล้ว'), ('growing', 'กำลังปลูก'), ('ready_to_harvest', 'พร้อมเก็บเกี่ยว'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('expired', 'หมดอายุ')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='store.plotbooking')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
