# Generated by Django 6.0.1 on 2026-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_plant_plot_plotbooking_plotbookingstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
    ]
