# Generated by Django 6.0.1 on 2026-08-24 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_plant_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='โค้ดส่วนลด'),
        ),
        migrations.CreateModel(
            name='GardenGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seedling', 'ต้นกล้า'), ('growing', 'กำลังโต'), ('mature', 'โตเต็มที่'), ('harvested', 'เก็บเกี่ยวแล้ว'), ('withered', 'เหี่ยว')], default='seedling', max_length=20, verbose_name='สถานะต้นไม้')),
                ('progress', models.FloatField(default=0.0, verbose_name='ความคืบหน้า (0-100)')),
                ('care_score', models.FloatField(default=0.0, verbose_name='คะแนนดูแล (0-1)')),
                ('last_watered_at', models.DateTimeField(blank=True, null=True, verbose_name='รดน้ำครั้งสุดท้าย')),
                ('last_fertilized_at', models.DateTimeField(blank=True, null=True, verbose_name='ใส่ปุ๋ยครั้งสุดท้าย')),
                ('water_streak', models.PositiveIntegerField(default=0, verbose_name='รดน้ำติดกัน (วัน)')),
                ('coins_earned', models.PositiveIntegerField(default=0, verbose_name='Coins ที่ได้รับ')),
                ('debug_days_added', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='store.plotbooking', verbose_name='การจอง')),
            ],
            options={
                'verbose_name': 'เกมสวน',
                'verbose_name_plural': 'เกมสวน',
            },
        ),
        migrations.CreateModel(
            name='PlayerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Session Key')),
                ('coins_balance', models.IntegerField(default=0, verbose_name='ยอด Coins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'กระเป๋าเหรียญ',
                'verbose_name_plural': 'กระเป๋าเหรียญ',
            },
        ),
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสคูปอง')),
                ('discount_amount', models.IntegerField(verbose_name='ส่วนลด (฿)')),
                ('coins_cost', models.IntegerField(verbose_name='ราคา (coins)')),
                ('is_used', models.BooleanField(default=False, verbose_name='ใช้แล้ว')),
                ('expires_at', models.DateTimeField(verbose_name='หมดอายุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='store.playerwallet', verbose_name='กระเป๋า')),
            ],
            options={
                'verbose_name': 'คูปองส่วนลด',
                'verbose_name_plural': 'คูปองส่วนลด',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='จำนวน (+ได้รับ / -ใช้)')),
                ('reason', models.CharField(choices=[('water', 'รดน้ำ'), ('fertilize', 'ใส่ปุ๋ย'), ('streak_bonus', 'โบนัสรดน้ำต่อเนื่อง'), ('harvest', 'เก็บเกี่ยว'), ('redeem', 'แลกส่วนลด')], max_length=20, verbose_name='เหตุผล')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.playerwallet', verbose_name='กระเป๋า')),
            ],
            options={
                'verbose_name': 'รายการเหรียญ',
                'verbose_name_plural': 'รายการเหรียญ',
                'ordering': ['-created_at'],
            },
        ),
    ]
