# Generated by Django 6.0.1 on 2026-08-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'สินค้า', 'verbose_name_plural': 'สินค้า'},
        ),
        migrations.AddField(
            model_name='plant',
            name='seed_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8, verbose_name='ค่าเมล็ดพันธุ์/ต้นกล้า (฿)'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
