# Generated by Django 6.0.1 on 2026-03-22 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม')),
                ('status', models.CharField(default='รอดำเนินการ', max_length=50, verbose_name='สถานะการจัดส่ง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่งซื้อ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งซื้อ')),
            ],
        ),
        migrations.CreateModel(
            name='VeggiePlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(max_length=100, verbose_name='ชื่อ/โซนแปลงผัก')),
                ('status', models.CharField(default='กำลังปลูก (รอเก็บเกี่ยว)', max_length=50, verbose_name='สถานะ')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่จอง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง')),
            ],
        ),
    ]
